### ISSUE TITLE
macOS installer probably needs a certificate update

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#529] opened 2020-09-17 12:52 UTC
I got the below message and am not allowed to use the application:
![Capture d’écran 2020-09-17 à 14 51 08](https://user-images.githubusercontent.com/21675885/93472716-59790200-f8f5-11ea-9ef1-e0b85a2c3450.png)

**Comment by rgaudin** [comment] 2020-09-17 13:05
Duplicate of #497. You can bypass this, as for other un notarized software by right-clicking the app and selecting open.

**Closed by rgaudin** 2020-09-17 13:05 UTC
Labels: bug

**Comment by Popolechien** [comment] 2020-09-17 13:11
Nope, cannot be bypassed anymore (lest I need to open up some other authorizations in my preferences maybe?)

**Comment by rgaudin** [comment] 2020-09-17 14:35
Just tested and works as I described.
<img width="532" alt="Screen Shot 2020-09-17 at 14 30 55" src="https://user-images.githubusercontent.com/57929/93485574-baeba180-f8f2-11ea-8366-5ee63551eaee.png">
<img width="419" alt="Screen Shot 2020-09-17 at 14 31 03" src="https://user-images.githubusercontent.com/57929/93485589-be7f2880-f8f2-11ea-9d30-63c9e7bc1137.png">
<img width="587" alt="Screen Shot 2020-09-17 at 14 31 09" src="https://user-images.githubusercontent.com/57929/93485594-bfb05580-f8f2-11ea-8293-3034483cc5de.png">
<img width="536" alt="Screen Shot 2020-09-17 at 14 31 49" src="https://user-images.githubusercontent.com/57929/93485598-c17a1900-f8f2-11ea-91ed-705fa68fb0df.png">

**Comment by Popolechien** [comment] 2020-09-17 14:40
Ok, works now for me as well. No idea what I missed or messed. Thanks.
