### ISSUE TITLE
Fails to build when Wifi password is kiwix ?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#579] opened 2021-04-24 19:13 UTC
Config https://cardshop.hotspot.kiwix.org/orders/L520R6084 failed with the following error message: `Invalid argument for wifi_pwd` 

But as far as I can see the password was simply `kiwix`.
Is this a bug or a feature?

**Comment by rgaudin** [comment] 2021-04-24 19:15
Too short of a string. closing as duplicate of the inputs checks not enforced in card shop

**Closed** 2021-04-24 19:15 UTC
Labels: bug, question

**Comment by kelson42** [comment] 2021-04-25 06:08
Duplicate of #83
