### ISSUE TITLE
Image fails to load on RPi 4B and asks user for newer software for the board

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-hotspot#568] opened 2021-04-18 13:13 UTC
User downloaded image from the cardshop. After flashing on a SD card no wifi network would appear, and upon plugging onto a screen he got an error message 'start4.eld: not compatible. This board requires newer software'  (see image attached)
![20210418_085740](https://user-images.githubusercontent.com/21675885/115146849-a2925f80-a058-11eb-8f53-b143c3c35e16.jpg)

**Comment by rgaudin** [comment] 2021-04-18 13:39
Duplicate of #556

**Closed** 2021-04-18 13:39 UTC
Labels: bug
